### ISSUE TITLE
Fix Conor's profile picture bug

### ISSUE THREAD

**Issue by ardacebi** [Kodular/kodular.github.io#17]
There is a bug on @conorshipp's profile picture that makes it look so bad next to the others. 

![screenshot-2018-5-9 makeroid app builder](https://user-images.githubusercontent.com/17576065/39783208-f28f9340-531c-11e8-83b5-8d71a4c78934.png)

**Comment by TurboProgramming** [comment]
Update: This bug seems to be a Firefox issue. I've tried Safari and Chrome and they both work completely fine with the image. But the issues definitely needs a fix as Firefox is a popular web browser too.
