### ISSUE TITLE
Makeroid Chatbot Integration

### ISSUE THREAD

**Issue by ardacebi** [Kodular/kodular.github.io#28]
Hey,

Is there any possibility to integrate the Makeroid Bot to the website with like a expandable fab or something? I found the iFrame code of the assistant.

This can be useful for new users to ask questions about it and give them more information without letting them to find info on the website. The bot really got intelligent right now. And it gets better and better with people talking to it.

<iframe
    width="350"
    height="430"
    src="https://console.dialogflow.com/api-client/demo/embedded/798b40a0-63e5-400a-98d3-6bb7c3ddcbc9">
</iframe>

---
Possible?

**Comment by ardacebi** [comment]
@barreeeiroo I don't have time to do anything these days because of school work, but you should have access to the management dashboard where you can work on it.

https://dialogflow.com/

**Comment by busybox11** [comment]
Maybe changing the name and the icon of the bot would be a good idea ^^'
