### ISSUE TITLE
Problem with the menu button

### ISSUE THREAD

**Issue by kamaravichow** [Kodular/kodular.github.io#49]
The menu button on the landing page toggles wrongly. When closed it shows the cross and when opened shows drawer icons.

**Comment by pavi2410** [comment]
I couldn't reproduce this issue

![image](https://user-images.githubusercontent.com/28837746/79696229-0db82300-8299-11ea-8768-0ad4fec40e83.png)
![image](https://user-images.githubusercontent.com/28837746/79696233-1872b800-8299-11ea-8a78-8f4d51a15b21.png)
